//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studentsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int BookId { get; set; }
        public string name { get; set; }
        public string author { get; set; }
        public string Отчество { get; set; }
        public string description { get; set; }
        public string Дата_рождения { get; set; }
        public string Год_поступления { get; set; }
        public string Год_окончания { get; set; }
        public string Образование { get; set; }
        public string Год_окончания_школы { get; set; }
        public string Номер_школы { get; set; }
        public string genre { get; set; }
        public string year { get; set; }
        public string picture { get; set; }
        public string Номер_телефона_родителей { get; set; }
        public string url { get; set; }
        public string dimensions { get; set; }
        public string weight { get; set; }
        public string Гражданство { get; set; }
        public string Документ_подтверждающий_гражданство { get; set; }
        public string Многодетная_семья { get; set; }
        public string barcode { get; set; }
        public string Срок_действия { get; set; }
        public string Основание_поощрение { get; set; }
        public string Основание_взыскания { get; set; }
        public string media { get; set; }
        public string От_какого_числа { get; set; }
        public string Внутриние_перемещения { get; set; }
        public string Характеристика_выпускника { get; set; }
        public string Трудоустройство_выпускника { get; set; }
        public string Продвижение_выпускника { get; set; }
        public decimal price { get; set; }
    }
}
