//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studentsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class students
    {
        public int Id { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Группа { get; set; }
        public string Дата_рождения { get; set; }
        public string Год_поступления { get; set; }
        public string Год_окончания { get; set; }
        public string Образование { get; set; }
        public string Год_окончания_школы { get; set; }
        public string Номер_школы { get; set; }
        public string Специальность { get; set; }
        public string Форма_обучения { get; set; }
        public string Номер_телефона_учащегося { get; set; }
        public string Номер_телефона_родителей { get; set; }
        public string Адрес { get; set; }
        public string Иностранный_язык { get; set; }
        public string Группа_здоровья { get; set; }
        public string Гражданство { get; set; }
        public string Документ_подтверждающий_гражданство { get; set; }
        public string Многодетная_семья { get; set; }
        public string Инвалидность { get; set; }
        public string Срок_действия { get; set; }
        public string Основание_поощрение { get; set; }
        public string Основание_взыскания { get; set; }
        public string Номер_диплома { get; set; }
        public string От_какого_числа { get; set; }
        public string Внутриние_перемещения { get; set; }
        public string Характеристика_выпускника { get; set; }
        public string Трудоустройство_выпускника { get; set; }
        public string Продвижение_выпускника { get; set; }
        public string Пропуски_без_уважительных_причин { get; set; }
    }
}
